/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dvbt2_p1insertion_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f662f12fabf6075c57d1befe8a296a33)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/dvbt2_p1insertion_cc.h>
// pydoc.h is automatically generated in the build directory
#include <dvbt2_p1insertion_cc_pydoc.h>

void bind_dvbt2_p1insertion_cc(py::module& m)
{

    using dvbt2_p1insertion_cc = ::gr::dtv::dvbt2_p1insertion_cc;


    py::class_<dvbt2_p1insertion_cc,
               gr::block,
               gr::basic_block,
               std::shared_ptr<dvbt2_p1insertion_cc>>(
        m, "dvbt2_p1insertion_cc", D(dvbt2_p1insertion_cc))

        .def(py::init(&dvbt2_p1insertion_cc::make),
             py::arg("fefmode"),
             py::arg("fefinterval"),
             py::arg("fftsize"),
             py::arg("guardinterval"),
             py::arg("numdatasyms"),
             py::arg("preamble"),
             py::arg("feffftsize"),
             py::arg("fefguardinterval"),
             py::arg("fefnumdatasyms"),
             py::arg("fefpreamble"),
             py::arg("showlevels"),
             py::arg("vclip"),
             D(dvbt2_p1insertion_cc, make))


        ;
}
